name: thin_u
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'
  flutter: '>=2.10.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  video_player: 2.7.2
  flick_video_player: ^0.5.0
  visibility_detector: ^0.3.0
  provider: ^6.0.1
  http: ^1.1.0
  youtube_player_flutter: ^8.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - images/CourseIntro0.jpg
    - images/CourseIntro1.jpg
    - images/CourseIntro2.jpg
    - images/CourseIntro3.jpg
    - images/CourseIntro4.jpg
    - images/CourseIntro5.jpg
    - images/CourseIntro6.jpg
    - images/CourseIntro7.jpg
    - images/CourseIntro8.jpg
    - images/CourseIntro9.jpg
    - images/CourseIntro9.jpg
    - images/CourseIntro10.jpg
    - videos/musicbox.mov


